services:
  minecraft:
    image: "ghcr.io/alpharomeo323/mc-doomedchunk:${IMAGE_TAG}"
    ports:
      - 25998:25565
    volumes:
      - type: bind
        source: data
        target: /data
    tty: true
    stdin_open: true
  starter:
    image: ghcr.io/ozraru/containerstarterbot
    volumes:
      - type: bind
        source: starter-config.yaml
        target: /data/config.yaml
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    
